Ultimately need to be able to describe entire system configuration options
through multiple different modules. So there needs to be modules for the
system and modules for home

An option should only be added if it has a meaningful impact on the configuration.
(i.e. no adding module options that don't do anything in the system).

* System Modules
Need to be able to define stuff like
- the hostname of the system
- the filesystem that should be used
- if encryption should be used
- if impermanence should be used
- the system type (laptop, desktop, server, vps, etc)
- graphics cards used in the system
- hard drives (?)

* Home modules
These will be options used to specify the home configuration of different users.
One crucial constraint is that I want the system to be usable by multiple different
people. Some people may be skilled in computer use and want something
like a super highly customized window manager with terminal based applications.
Other users might just want a basic desktop environment and some GUI applications.
The system needs to be able to accomodate both types of user through the module
configuration.

- Needs some kind of way to specify multiple users for a single system
- For each user needs to be able to specify different tags/roles
  - The tags will indicate what kind of software experience will be used
  - Not sure if this is good idea or if maybe it would be best to just
    specify home configurations for each user explicitly.
- Either way, the workstation itself needs to have the concept of a role
  - The role could be something like (workstation, server, gamestation (?))
  - These roles will be used to install different kinds of software
    and configurations for the users of the machine.
